-- Connect as admin user first
-- Create CDC user
CREATE USER cdc_user IDENTIFIED BY "CdcUser123!"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO cdc_user;
GRANT CREATE SESSION TO cdc_user;
GRANT SELECT ANY TRANSACTION TO cdc_user;
GRANT SELECT ANY DICTIONARY TO cdc_user;
GRANT EXECUTE_CATALOG_ROLE TO cdc_user;
GRANT SELECT_CATALOG_ROLE TO cdc_user;
GRANT FLASHBACK ANY TABLE TO cdc_user;

-- Enable supplemental logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create demo user
CREATE USER demo_user IDENTIFIED BY "DemoUser123!"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO demo_user;
GRANT CREATE TABLE TO demo_user;

-- Switch to demo_user
ALTER SESSION SET CURRENT_SCHEMA = demo_user;

-- Create S_CONTACT table (Siebel CRM style)
CREATE TABLE S_CONTACT (
    ROW_ID              VARCHAR2(15) NOT NULL PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) DEFAULT '0-1' NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) DEFAULT '0-1' NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    
    -- Contact Information
    FST_NAME            VARCHAR2(50),
    LAST_NAME           VARCHAR2(50) NOT NULL,
    MID_NAME            VARCHAR2(50),
    BIRTH_DT            DATE,
    SOC_SECURITY_NUM    VARCHAR2(40),
    
    -- Contact Details
    EMAIL_ADDR          VARCHAR2(350),
    WORK_PH_NUM         VARCHAR2(40),
    CELL_PH_NUM         VARCHAR2(40),
    HOME_PH_NUM         VARCHAR2(40),
    
    -- Address Information
    ADDR                VARCHAR2(200),
    CITY                VARCHAR2(50),
    STATE               VARCHAR2(50),
    POSTAL_CD           VARCHAR2(30),
    COUNTRY             VARCHAR2(30),
    
    -- Status
    CONTACT_STAT_CD     VARCHAR2(30) DEFAULT 'Active',
    
    -- Integration
    INTEGRATION_ID      VARCHAR2(30),
    
    -- Additional Siebel fields
    PR_DEPT_OU_ID       VARCHAR2(15),
    PR_POSTN_ID         VARCHAR2(15),
    PERSON_UID          VARCHAR2(100),
    SUPPRESS_EMAIL_FLG  CHAR(1) DEFAULT 'N',
    SUPPRESS_CALL_FLG   CHAR(1) DEFAULT 'N'
);

-- Create indexes
CREATE INDEX IDX_S_CONTACT_EMAIL ON S_CONTACT(EMAIL_ADDR);
CREATE INDEX IDX_S_CONTACT_NAME ON S_CONTACT(LAST_NAME, FST_NAME);
CREATE INDEX IDX_S_CONTACT_INTEG ON S_CONTACT(INTEGRATION_ID);

-- Enable supplemental logging on table
ALTER TABLE S_CONTACT ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Grant permissions to CDC user
GRANT SELECT ON demo_user.S_CONTACT TO cdc_user;
GRANT FLASHBACK ON demo_user.S_CONTACT TO cdc_user;