-- Connect as admin user first
-- Create CRM schema user
CREATE USER crm_user IDENTIFIED BY "CrmUser123!"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO crm_user;
GRANT CREATE TABLE TO crm_user;
GRANT CREATE SEQUENCE TO crm_user;
GRANT CREATE TRIGGER TO crm_user;

-- Create CDC user
CREATE USER cdc_user IDENTIFIED BY "CdcUser123!"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

-- Grant CDC privileges
GRANT CONNECT, RESOURCE TO cdc_user;
GRANT CREATE SESSION TO cdc_user;
GRANT EXECUTE_CATALOG_ROLE TO cdc_user;
GRANT SELECT ANY TRANSACTION TO cdc_user;
GRANT SELECT ANY DICTIONARY TO cdc_user;
GRANT LOGMINING TO cdc_user;
GRANT FLASHBACK ANY TABLE TO cdc_user;

-- Enable supplemental logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Connect as crm_user
-- Create CRM tables based on Siebel CRM structure

-- S_CONTACT: Contact/Customer information
CREATE TABLE crm_user.S_CONTACT (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    FST_NAME            VARCHAR2(50),
    LAST_NAME           VARCHAR2(50) NOT NULL,
    MID_NAME            VARCHAR2(50),
    FULL_NAME           VARCHAR2(150),
    EMP_FLG             CHAR(1) DEFAULT 'N',
    PRIV_FLG            CHAR(1) DEFAULT 'N',
    SUPPRESS_EMAIL_FLG  CHAR(1) DEFAULT 'N',
    SUPPRESS_CALL_FLG   CHAR(1) DEFAULT 'N',
    EMAIL_ADDR          VARCHAR2(350),
    WORK_PH_NUM         VARCHAR2(40),
    CELL_PH_NUM         VARCHAR2(40),
    HOME_PH_NUM         VARCHAR2(40),
    BIRTH_DT            DATE,
    SOC_SECURITY_NUM    VARCHAR2(20),
    MARITAL_STAT_CD     VARCHAR2(30),
    CITIZENSHIP_CD      VARCHAR2(30),
    NATIONALITY_CD      VARCHAR2(30),
    PR_DEPT_OU_ID       VARCHAR2(15),
    PR_POSTN_ID         VARCHAR2(15),
    PERSON_UID          VARCHAR2(100),
    INTEGRATION_ID      VARCHAR2(30),
    STATUS_CD           VARCHAR2(30) DEFAULT 'ACTIVE'
);

-- S_ORG_EXT: Account/Organization information
CREATE TABLE crm_user.S_ORG_EXT (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    NAME                VARCHAR2(100) NOT NULL,
    LOC                 VARCHAR2(50),
    OU_TYPE_CD          VARCHAR2(30),
    PR_TERR_ID          VARCHAR2(15),
    CUST_STAT_CD        VARCHAR2(30),
    PARTNER_FLG         CHAR(1) DEFAULT 'N',
    DIVN_TYPE_CD        VARCHAR2(30),
    ACCNT_TYPE_CD       VARCHAR2(30),
    DUNS_NUM            VARCHAR2(15),
    SIC_CD              VARCHAR2(20),
    FISCAL_YR_END_MO    VARCHAR2(30),
    NUM_EMPLOYEES       NUMBER(10),
    ANNUAL_REV          NUMBER(22,7),
    ANNUAL_REV_CURCY_CD VARCHAR2(20),
    INTEGRATION_ID      VARCHAR2(30),
    STATUS_CD           VARCHAR2(30) DEFAULT 'ACTIVE'
);

-- S_OPTY: Opportunity information
CREATE TABLE crm_user.S_OPTY (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    NAME                VARCHAR2(100) NOT NULL,
    TYPE_CD             VARCHAR2(30),
    PR_PROD_ID          VARCHAR2(15),
    ACCNT_ID            VARCHAR2(15),
    PR_CON_ID           VARCHAR2(15),
    CURCY_CD            VARCHAR2(20),
    EXCH_DT             DATE,
    EFF_START_DT        DATE,
    EFF_END_DT          DATE,
    CLOSE_DT            DATE,
    SUM_REVN_AMT        NUMBER(22,7),
    SUM_REVN_CURCY_CD   VARCHAR2(20),
    SUM_WIN_PROB        NUMBER(5,2),
    STG_STATUS_CD       VARCHAR2(30),
    LEAD_QUAL_CD        VARCHAR2(30),
    PR_POSTN_ID         VARCHAR2(15),
    PR_TERR_ID          VARCHAR2(15),
    INTEGRATION_ID      VARCHAR2(30),
    OPTY_CD             VARCHAR2(30),
    STATUS_CD           VARCHAR2(30) DEFAULT 'ACTIVE'
);

-- S_ORDER: Order/Quote information
CREATE TABLE crm_user.S_ORDER (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    ORDER_NUM           VARCHAR2(30) NOT NULL UNIQUE,
    REV_NUM             NUMBER(10) DEFAULT 1,
    ORDER_DT            DATE,
    ORDER_TYPE_CD       VARCHAR2(30),
    ACCNT_ID            VARCHAR2(15),
    CONTACT_ID          VARCHAR2(15),
    OPTY_ID             VARCHAR2(15),
    CURCY_CD            VARCHAR2(20),
    EXCH_DT             DATE,
    SHIP_DT             DATE,
    REQ_SHIP_DT         DATE,
    FREIGHT_AMT         NUMBER(22,7),
    FREIGHT_CURCY_CD    VARCHAR2(20),
    TAX_AMT             NUMBER(22,7),
    ITEM_TOTAL          NUMBER(22,7),
    ORDER_TOTAL         NUMBER(22,7),
    STATUS_CD           VARCHAR2(30),
    PAYMENT_TERM_CD     VARCHAR2(30),
    PAYMENT_TYPE_CD     VARCHAR2(30),
    INTEGRATION_ID      VARCHAR2(30),
    ACTIVE_FLG          CHAR(1) DEFAULT 'Y'
);

-- S_ORDER_ITEM: Order line items
CREATE TABLE crm_user.S_ORDER_ITEM (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    ORDER_ID            VARCHAR2(15) NOT NULL,
    LINE_NUM            NUMBER(10) NOT NULL,
    PROD_ID             VARCHAR2(15),
    PROD_NAME           VARCHAR2(100),
    PART_NUM            VARCHAR2(50),
    QTY                 NUMBER(22,7),
    QTY_SHIPPED         NUMBER(22,7),
    UNIT_PRICE          NUMBER(22,7),
    UNIT_PRICE_CURCY_CD VARCHAR2(20),
    EXTENDED_AMT        NUMBER(22,7),
    DISCOUNT_AMT        NUMBER(22,7),
    DISCOUNT_PERCENT    NUMBER(5,2),
    TAX_AMT             NUMBER(22,7),
    LINE_TOTAL          NUMBER(22,7),
    STATUS_CD           VARCHAR2(30),
    INTEGRATION_ID      VARCHAR2(30),
    ACTION_CD           VARCHAR2(30) DEFAULT 'ADD',
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES S_ORDER(ROW_ID)
);

-- S_ACTIVITY: Activity/Task information
CREATE TABLE crm_user.S_ACTIVITY (
    ROW_ID              VARCHAR2(15) PRIMARY KEY,
    CREATED             DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(15) NOT NULL,
    LAST_UPD            DATE DEFAULT SYSDATE NOT NULL,
    LAST_UPD_BY         VARCHAR2(15) NOT NULL,
    MODIFICATION_NUM    NUMBER(10) DEFAULT 0 NOT NULL,
    CONFLICT_ID         VARCHAR2(15) DEFAULT '0' NOT NULL,
    ACTIVITY_UID        VARCHAR2(50),
    TYPE_CD             VARCHAR2(30),
    SUBTYPE_CD          VARCHAR2(30),
    PR_SUBJECT          VARCHAR2(250),
    DESC_TEXT           VARCHAR2(2000),
    ACCNT_ID            VARCHAR2(15),
    CONTACT_ID          VARCHAR2(15),
    OPTY_ID             VARCHAR2(15),
    START_DT            DATE,
    END_DT              DATE,
    DURATION_MIN        NUMBER(10),
    PR_EMP_ID           VARCHAR2(15),
    STATUS_CD           VARCHAR2(30),
    PRIORITY_CD         VARCHAR2(30),
    ALARM_FLAG          CHAR(1) DEFAULT 'N',
    TODO_PLAN_START_DT  DATE,
    TODO_PLAN_END_DT    DATE,
    TODO_ACTL_END_DT    DATE,
    INTEGRATION_ID      VARCHAR2(30),
    ACTIVE_FLG          CHAR(1) DEFAULT 'Y'
);

-- Create indexes for better performance
CREATE INDEX IDX_CONTACT_EMAIL ON crm_user.S_CONTACT(EMAIL_ADDR);
CREATE INDEX IDX_CONTACT_INTEG ON crm_user.S_CONTACT(INTEGRATION_ID);
CREATE INDEX IDX_ORG_NAME ON crm_user.S_ORG_EXT(NAME);
CREATE INDEX IDX_ORG_INTEG ON crm_user.S_ORG_EXT(INTEGRATION_ID);
CREATE INDEX IDX_OPTY_ACCNT ON crm_user.S_OPTY(ACCNT_ID);
CREATE INDEX IDX_OPTY_STATUS ON crm_user.S_OPTY(STATUS_CD);
CREATE INDEX IDX_ORDER_NUM ON crm_user.S_ORDER(ORDER_NUM);
CREATE INDEX IDX_ORDER_ACCNT ON crm_user.S_ORDER(ACCNT_ID);
CREATE INDEX IDX_ORDER_CONTACT ON crm_user.S_ORDER(CONTACT_ID);
CREATE INDEX IDX_ORDER_ITEM_ORDER ON crm_user.S_ORDER_ITEM(ORDER_ID);
CREATE INDEX IDX_ACTIVITY_ACCNT ON crm_user.S_ACTIVITY(ACCNT_ID);
CREATE INDEX IDX_ACTIVITY_CONTACT ON crm_user.S_ACTIVITY(CONTACT_ID);

-- Enable supplemental logging on all tables
ALTER TABLE crm_user.S_CONTACT ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE crm_user.S_ORG_EXT ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE crm_user.S_OPTY ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE crm_user.S_ORDER ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE crm_user.S_ORDER_ITEM ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE crm_user.S_ACTIVITY ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Grant permissions to CDC user
GRANT SELECT, FLASHBACK ON crm_user.S_CONTACT TO cdc_user;
GRANT SELECT, FLASHBACK ON crm_user.S_ORG_EXT TO cdc_user;
GRANT SELECT, FLASHBACK ON crm_user.S_OPTY TO cdc_user;
GRANT SELECT, FLASHBACK ON crm_user.S_ORDER TO cdc_user;
GRANT SELECT, FLASHBACK ON crm_user.S_ORDER_ITEM TO cdc_user;
GRANT SELECT, FLASHBACK ON crm_user.S_ACTIVITY TO cdc_user;