-- Enable CDC
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create CDC user
CREATE USER cdc_user IDENTIFIED BY "CdcDemo2024!";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO cdc_user;
GRANT UNLIMITED TABLESPACE TO cdc_user;

-- Create Debezium user
CREATE USER debezium IDENTIFIED BY "D3b3z1um#2024";
GRANT CREATE SESSION TO debezium;
GRANT SELECT ON V_$DATABASE TO debezium;
GRANT FLASHBACK ANY TABLE TO debezium;
GRANT SELECT ANY TRANSACTION TO debezium;
GRANT LOGMINING TO debezium;

-- Create tables with CDC enabled...