-- Create CDC user
CREATE USER cdc_user IDENTIFIED BY "CdcDemo2024!";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO cdc_user;
GRANT UNLIMITED TABLESPACE TO cdc_user;

-- Enable supplemental logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create source tables with timestamps
CREATE TABLE cdc_user.customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) UNIQUE NOT NULL,
    phone VARCHAR2(20),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cdc_user.products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(200) NOT NULL,
    category VARCHAR2(100),
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cdc_user.orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMBER(10,2),
    status VARCHAR2(50) DEFAULT 'PENDING',
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) 
        REFERENCES cdc_user.customers(customer_id)
);

-- Create triggers for updated_date
CREATE OR REPLACE TRIGGER customers_update_trigger
BEFORE UPDATE ON cdc_user.customers
FOR EACH ROW
BEGIN
    :NEW.updated_date := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER products_update_trigger
BEFORE UPDATE ON cdc_user.products
FOR EACH ROW
BEGIN
    :NEW.updated_date := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER orders_update_trigger
BEFORE UPDATE ON cdc_user.orders
FOR EACH ROW
BEGIN
    :NEW.updated_date := CURRENT_TIMESTAMP;
END;
/

-- Grant permissions for Debezium
GRANT SELECT ON cdc_user.customers TO debezium;
GRANT SELECT ON cdc_user.products TO debezium;
GRANT SELECT ON cdc_user.orders TO debezium;
GRANT FLASHBACK ANY TABLE TO debezium;
GRANT SELECT ANY TRANSACTION TO debezium;
GRANT SELECT ON V_$DATABASE TO debezium;