# kubernetes/debezium/02-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debezium-connect
  namespace: kafka
  annotations:
    eks.amazonaws.com/role-arn: ${MSK_ACCESS_ROLE_ARN}
