# kubernetes/debezium/03-kafka-connect.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: ${MSK_BOOTSTRAP_SERVERS}
  
  authentication:
    type: aws-iam
    
  config:
    group.id: debezium-connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    
    # Replication factors
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    
    # Performance tuning
    producer.linger.ms: 100
    producer.batch.size: 500000
    producer.compression.type: lz4
    consumer.fetch.min.bytes: 102400
    
  build:
    output:
      type: docker
      image: ${ECR_REGISTRY}/debezium-connect-oracle:latest
      pushSecret: ecr-secret
    plugins:
      - name: debezium-oracle-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-oracle/2.5.1.Final/debezium-connector-oracle-2.5.1.Final-plugin.tar.gz
      - name: kafka-connect-msk-iam-auth
        artifacts:
          - type: jar
            url: https://github.com/aws/aws-msk-iam-auth/releases/download/v1.1.9/aws-msk-iam-auth-1.1.9-all.jar
            
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
      
  jvmOptions:
    -Xms: 256m
    -Xmx: 768m
    
  logging:
    type: inline
    loggers:
      connect.root.logger.level: INFO
      io.debezium: DEBUG
      
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
    
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
    
  template:
    pod:
      metadata:
        labels:
          app: debezium-connect
          project: demo_rt_the_one
      serviceAccountName: debezium-connect
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                  - debezium-connect-cluster
              topologyKey: kubernetes.io/hostname
