# kubernetes/kafka-streams/01-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pii-masking-config
  namespace: kafka
data:
  application.properties: |
    # Kafka Streams Configuration
    application.id=pii-masking-app
    bootstrap.servers=${MSK_BOOTSTRAP_SERVERS}
    
    # Processing
    num.stream.threads=4
    processing.guarantee=exactly_once_v2
    cache.max.bytes.buffering=10485760
    commit.interval.ms=1000
    
    # Consumer
    auto.offset.reset=earliest
    max.poll.records=1000
    
    # MSK IAM
    security.protocol=SASL_SSL
    sasl.mechanism=AWS_MSK_IAM
    sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
    
  log4j.properties: |
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %-5p [%t] %c{2} - %m%n
    log4j.logger.com.demo=DEBUG
    log4j.logger.org.apache.kafka.streams=WARN
