# kubernetes/kafka-streams/02-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pii-masking
  namespace: kafka
  labels:
    app: pii-masking
    project: demo_rt_the_one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pii-masking
  template:
    metadata:
      labels:
        app: pii-masking
        project: demo_rt_the_one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: pii-masking
      containers:
      - name: pii-masking
        image: ${ECR_REGISTRY}/pii-masking:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: ${MSK_BOOTSTRAP_SERVERS}
        - name: USE_MSK_IAM
          value: "true"
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: JAVA_OPTS
          # value: "-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=20"
          value: "-Xmx768m -Xms256m -XX:+UseG1GC"  # ลด heap size
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: pii-masking-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pii-masking
              topologyKey: kubernetes.io/hostname
