apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: cdc-apps
data:
  config.yaml: |
    oracle:
      schema: crm_user
      tables:
        - s_contact
        - s_org_ext
        - s_opty
        - s_order
        - s_order_item
        - s_activity
    kafka:
      batch_size: 5000
      poll_interval: 1.0
    app:
      port: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: producer-secrets
  namespace: cdc-apps
type: Opaque
stringData:
  oracle-endpoint: "${ORACLE_ENDPOINT}"
  oracle-username: "admin"
  oracle-password: "${ORACLE_PASSWORD}"
  kafka-brokers: "cdc-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-producer
  namespace: cdc-apps
  labels:
    app: cdc-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc-producer
  template:
    metadata:
      labels:
        app: cdc-producer
    spec:
      containers:
      - name: producer
        image: ${ECR_REPO}/cdc-producer:latest
        imagePullPolicy: Always
        env:
        - name: ORACLE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: oracle-endpoint
        - name: ORACLE_USERNAME
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: oracle-username
        - name: ORACLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: oracle-password
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: producer-secrets
              key: kafka-brokers
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: producer-config
---
apiVersion: v1
kind: Service
metadata:
  name: cdc-producer
  namespace: cdc-apps
spec:
  selector:
    app: cdc-producer
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  type: ClusterIP